import {
  Inbox,
  Star,
  Send,
  FileText,
  AlertTriangle,
  Bookmark,
  Trash2,
} from "lucide-react";

export const sidebarItems = [
  {
    id: "main",
    section: "Main",
    items: [
      { title: "Inbox", href: "/dashboard/inbox?folder=Inbox", icon: Inbox },
      { title: "Starred", href: "/dashboard/inbox?folder=Starred", icon: Star },
      { title: "Sent", href: "/dashboard/inbox?folder=Sent", icon: Send },
      { title: "Draft", href: "/dashboard/inbox?folder=Draft", icon: FileText },
      {
        title: "Spam",
        href: "/dashboard/inbox?folder=Spam",
        icon: AlertTriangle,
      },
      {
        title: "Important",
        href: "/dashboard/inbox?folder=Important",
        icon: Bookmark,
      },
      { title: "Bin", href: "/dashboard/inbox?folder=Bin", icon: Trash2 },
    ],
  },
];

export const defaultLabelColors = [
  "#4ADE80",
  "#60A5FA",
  "#FB923C",
  "#C084FC",
  "#F87171",
  "#FBBF24",
];

export const initialLabels = [
  { name: "Primary", color: "#4ADE80" },
  { name: "Social", color: "#60A5FA" },
  { name: "Work", color: "#FB923C" },
  { name: "Friends", color: "#C084FC" },
];

export const initialEmails = [
  {
    id: 1,
    name: "Julia Jalal",
    label: "Primary",
    message: "Our Bachelor of Commerce program is ACBSP-accredited.",
    time: "8:38 AM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 2,
    name: "Minerva Barnett",
    label: "Work",
    message: "Get Best Advertiser In Your Side Pocket",
    time: "8:13 AM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 3,
    name: "Peter Lewis",
    label: "Friends",
    message: "Vacation Home Rental Success",
    time: "7:52 PM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 4,
    name: "Anthony Bingos",
    label: "Social",
    message: "Free Classifieds Using Them To Promote Your Stuff",
    time: "7:52 PM",
    starred: true,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 5,
    name: "Clifford Morgan",
    label: "Social",
    message: "Enhance Your Brand Potential With Giant Blimps",
    time: "4:13 PM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 6,
    name: "Cecilia Webster",
    label: "Friends",
    message: "Always Look On The Bright Side Of Life",
    time: "3:52 PM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 7,
    name: "Harvey Manning",
    label: "Work",
    message: "Curling Irons Are As Individual As The Women",
    time: "2:30 PM",
    starred: true,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 8,
    name: "Sandra Blake",
    label: "Primary",
    message: "Q3 financial reports are ready for your review",
    time: "1:10 PM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 9,
    name: "Tom Nguyen",
    label: "Work",
    message: "Meeting reschedule request for Monday",
    time: "12:00 PM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 10,
    name: "Aisha Karim",
    label: "Social",
    message: "Your invite to the design showcase event",
    time: "11:30 AM",
    starred: true,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 11,
    name: "Leo Fischer",
    label: "Friends",
    message: "Weekend hiking trip — are you joining?",
    time: "10:05 AM",
    starred: false,
    checked: false,
    folder: "Inbox",
  },
  {
    id: 12,
    name: "Priya Sharma",
    label: "Primary",
    message: "Renewal notice for your subscription plan",
    time: "9:45 AM",
    starred: false,
    checked: false,
    folder: "Spam",
  },
  {
    id: 13,
    name: "Carlos Mendez",
    label: "Work",
    message: "Action required: complete your onboarding steps",
    time: "9:00 AM",
    starred: false,
    checked: false,
    folder: "Sent",
  },
  {
    id: 14,
    name: "Nina Okonkwo",
    label: "Social",
    message: "You have a new follower on your profile",
    time: "8:20 AM",
    starred: false,
    checked: false,
    folder: "Draft",
  },
];
