export const collections = [
  {
    id: "breakfast-special",
    title: "Breakfast Special",
    price: "15",
    img: "/home2.jpg",
    categories: "Morning Picks",
    variants: 3,
  },
  {
    id: "classic-burger",
    title: "Classic Burger",
    price: "12",
    img: "/home.jpg",
    categories: "Burgers",
    variants: 5,
  },
  {
    id: "french-pancakes",
    title: "French Pancakes",
    price: "10",
    img: "/home2.jpg",
    categories: "Desserts",
    variants: 2,
  },
  {
    id: "crispy-pizza",
    title: "Crispy Pizza",
    price: "18",
    img: "/home.jpg",
    categories: "Pizza",
    variants: 4,
  },
  {
    id: "fresh-salad-healthy",
    title: "Fresh Salad",
    price: "9",
    img: "/home2.jpg",
    categories: "Healthy",
    variants: 3,
  },
];