 
export const rows = [
    {
        id: 1,
        image: "https://via.placeholder.com/40",
        productId: "P001",
        category: "Category 1",
        price: "$10",
        pieces: 100,
        availablecolor: "Red, Blue",
    },
    {
        id: 2,
        image: "https://via.placeholder.com/40",
        productId: "P002",
        category: "Category 2",
        price: "$20",
        pieces: 50,
        availablecolor: "Green, Yellow",
    },
    {
        id: 3,
        image: "https://via.placeholder.com/40",
        productId: "P003",
        category: "Category 3",
        price: "$30",
        pieces: 25,
        availablecolor: "Black, White",
    },
    {
        id: 4,  
        image: "https://via.placeholder.com/40",
        productId: "P004",
        category: "Category 4",
        price: "$40",
        pieces: 10,
        availablecolor: "Purple, Orange",
    },
    {
        id: 5,
        image: "https://via.placeholder.com/40",
        productId: "P005",
        category: "Category 5",
        price: "$50",
        pieces: 5,
        availablecolor: "Pink, Brown",
    },
    {
        id: 6,
        image: "https://via.placeholder.com/40",
        productId: "P006",
        category: "Category 6",
        price: "$60",
        pieces: 2,
        availablecolor: "Gray, Silver",
    },
    {
        id: 7,
        image: "https://via.placeholder.com/40",
        productId: "P007",
        category: "Category 7",
        price: "$70",
        pieces: 1,
        availablecolor: "Gold, Rose Gold",
    },
    {
        id: 8,
        image: "https://via.placeholder.com/40",
        productId: "P008",
        category: "Category 8",
        price: "$80",
        pieces: 1,
        availablecolor: "Black, White",
    }

]